name: google_maps_apis
description: Google Maps Web Services [API](https://developers.google.com/maps/web-services)
version: 5.0.0
repository: https://github.com/luis901101/google_maps_apis
issue_tracker: https://github.com/luis901101/google_maps_apis/issues
topics:
  - google-apis
  - google-place
  - google-place-new-api
  - google-directions
  - google-geocoding

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  http: '>=0.13.0 <2.0.0'
  json_annotation: ^4.10.0
  copy_with_extension: ^12.0.0
  collection: ^1.19.1
  retrofit: ^4.9.2
  dio: ^5.9.1
  meta: ^1.17.0 # meta is pinned to version 1.17.0 by flutter_test from the flutter SDK.
  uuid: ^4.5.2

dev_dependencies:
  test: ^1.29.0
  lints: ^6.1.0
  build_runner: ^2.11.1
  retrofit_generator: ^10.2.3
  json_serializable: ^6.12.0
  copy_with_extension_gen: ^12.0.0
  coverage: ^1.15.0
